// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe-o2eNyGbuqbCvmK7Pwmmd8YFs0vdur0',
    appId: '1:52681180747:android:bf630d67a956ed0edbefce',
    messagingSenderId: '52681180747',
    projectId: 'employeecemtacfacedetection',
    storageBucket: 'employeecemtacfacedetection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEVUNnmMmZq2Qj50G5eoTkVPTq647FdNg',
    appId: '1:255239208693:ios:8b20b1a41e5a27fdb2cfbc',
    messagingSenderId: '255239208693',
    projectId: 'cn-attendance',
    storageBucket: 'cn-attendance.appspot.com',
    iosBundleId: 'com.example.cnattendance',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa26Sy8Loof4weZqJX257epDyNkoUpX2U',
    appId: '1:52681180747:web:f52c9edb8a5c9131dbefce',
    messagingSenderId: '52681180747',
    projectId: 'employeecemtacfacedetection',
    authDomain: 'employeecemtacfacedetection.firebaseapp.com',
    storageBucket: 'employeecemtacfacedetection.firebasestorage.app',
    measurementId: 'G-DECN1QD5QR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz9Z8OeJolwFzk5TvUD7waDEhpBH-k7Is',
    appId: '1:329791479566:ios:e0cdede8975857833c415f',
    messagingSenderId: '329791479566',
    projectId: 'workermodelcemtacbiomatric',
    storageBucket: 'workermodelcemtacbiomatric.firebasestorage.app',
    iosBundleId: 'com.cninfotech.digitalhrs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa26Sy8Loof4weZqJX257epDyNkoUpX2U',
    appId: '1:52681180747:web:2a945091d060eac7dbefce',
    messagingSenderId: '52681180747',
    projectId: 'employeecemtacfacedetection',
    authDomain: 'employeecemtacfacedetection.firebaseapp.com',
    storageBucket: 'employeecemtacfacedetection.firebasestorage.app',
    measurementId: 'G-RKW1E8XWFM',
  );

}